apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bentobox.fullname" . }}
  labels:
    {{- include "bentobox.labels" . | nindent 4 }}
data:
  config.json: |
    {{ .Values.config | toJson }}
